[Hexagon0]
Meter=Shape
Group=Color
X=((50 * (0 % 9) * 3) + (Floor(0/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(0/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon1]
Meter=Shape
Group=Color
X=((50 * (1 % 9) * 3) + (Floor(1/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(1/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon2]
Meter=Shape
Group=Color
X=((50 * (2 % 9) * 3) + (Floor(2/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(2/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon3]
Meter=Shape
Group=Color
X=((50 * (3 % 9) * 3) + (Floor(3/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(3/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon4]
Meter=Shape
Group=Color
X=((50 * (4 % 9) * 3) + (Floor(4/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(4/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon5]
Meter=Shape
Group=Color
X=((50 * (5 % 9) * 3) + (Floor(5/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(5/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon6]
Meter=Shape
Group=Color
X=((50 * (6 % 9) * 3) + (Floor(6/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(6/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon7]
Meter=Shape
Group=Color
X=((50 * (7 % 9) * 3) + (Floor(7/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(7/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon8]
Meter=Shape
Group=Color
X=((50 * (8 % 9) * 3) + (Floor(8/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(8/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon9]
Meter=Shape
Group=Color
X=((50 * (9 % 9) * 3) + (Floor(9/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(9/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon10]
Meter=Shape
Group=Color
X=((50 * (10 % 9) * 3) + (Floor(10/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(10/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon11]
Meter=Shape
Group=Color
X=((50 * (11 % 9) * 3) + (Floor(11/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(11/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon12]
Meter=Shape
Group=Color
X=((50 * (12 % 9) * 3) + (Floor(12/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(12/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon13]
Meter=Shape
Group=Color
X=((50 * (13 % 9) * 3) + (Floor(13/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(13/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon14]
Meter=Shape
Group=Color
X=((50 * (14 % 9) * 3) + (Floor(14/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(14/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon15]
Meter=Shape
Group=Color
X=((50 * (15 % 9) * 3) + (Floor(15/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(15/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon16]
Meter=Shape
Group=Color
X=((50 * (16 % 9) * 3) + (Floor(16/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(16/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon17]
Meter=Shape
Group=Color
X=((50 * (17 % 9) * 3) + (Floor(17/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(17/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon18]
Meter=Shape
Group=Color
X=((50 * (18 % 9) * 3) + (Floor(18/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(18/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon19]
Meter=Shape
Group=Color
X=((50 * (19 % 9) * 3) + (Floor(19/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(19/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon20]
Meter=Shape
Group=Color
X=((50 * (20 % 9) * 3) + (Floor(20/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(20/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon21]
Meter=Shape
Group=Color
X=((50 * (21 % 9) * 3) + (Floor(21/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(21/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon22]
Meter=Shape
Group=Color
X=((50 * (22 % 9) * 3) + (Floor(22/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(22/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon23]
Meter=Shape
Group=Color
X=((50 * (23 % 9) * 3) + (Floor(23/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(23/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon24]
Meter=Shape
Group=Color
X=((50 * (24 % 9) * 3) + (Floor(24/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(24/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon25]
Meter=Shape
Group=Color
X=((50 * (25 % 9) * 3) + (Floor(25/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(25/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon26]
Meter=Shape
Group=Color
X=((50 * (26 % 9) * 3) + (Floor(26/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(26/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon27]
Meter=Shape
Group=Color
X=((50 * (27 % 9) * 3) + (Floor(27/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(27/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon28]
Meter=Shape
Group=Color
X=((50 * (28 % 9) * 3) + (Floor(28/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(28/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon29]
Meter=Shape
Group=Color
X=((50 * (29 % 9) * 3) + (Floor(29/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(29/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon30]
Meter=Shape
Group=Color
X=((50 * (30 % 9) * 3) + (Floor(30/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(30/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon31]
Meter=Shape
Group=Color
X=((50 * (31 % 9) * 3) + (Floor(31/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(31/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon32]
Meter=Shape
Group=Color
X=((50 * (32 % 9) * 3) + (Floor(32/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(32/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon33]
Meter=Shape
Group=Color
X=((50 * (33 % 9) * 3) + (Floor(33/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(33/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon34]
Meter=Shape
Group=Color
X=((50 * (34 % 9) * 3) + (Floor(34/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(34/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon35]
Meter=Shape
Group=Color
X=((50 * (35 % 9) * 3) + (Floor(35/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(35/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon36]
Meter=Shape
Group=Color
X=((50 * (36 % 9) * 3) + (Floor(36/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(36/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon37]
Meter=Shape
Group=Color
X=((50 * (37 % 9) * 3) + (Floor(37/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(37/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon38]
Meter=Shape
Group=Color
X=((50 * (38 % 9) * 3) + (Floor(38/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(38/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon39]
Meter=Shape
Group=Color
X=((50 * (39 % 9) * 3) + (Floor(39/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(39/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon40]
Meter=Shape
Group=Color
X=((50 * (40 % 9) * 3) + (Floor(40/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(40/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon41]
Meter=Shape
Group=Color
X=((50 * (41 % 9) * 3) + (Floor(41/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(41/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon42]
Meter=Shape
Group=Color
X=((50 * (42 % 9) * 3) + (Floor(42/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(42/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon43]
Meter=Shape
Group=Color
X=((50 * (43 % 9) * 3) + (Floor(43/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(43/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon44]
Meter=Shape
Group=Color
X=((50 * (44 % 9) * 3) + (Floor(44/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(44/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon45]
Meter=Shape
Group=Color
X=((50 * (45 % 9) * 3) + (Floor(45/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(45/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon46]
Meter=Shape
Group=Color
X=((50 * (46 % 9) * 3) + (Floor(46/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(46/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon47]
Meter=Shape
Group=Color
X=((50 * (47 % 9) * 3) + (Floor(47/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(47/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon48]
Meter=Shape
Group=Color
X=((50 * (48 % 9) * 3) + (Floor(48/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(48/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon49]
Meter=Shape
Group=Color
X=((50 * (49 % 9) * 3) + (Floor(49/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(49/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon50]
Meter=Shape
Group=Color
X=((50 * (50 % 9) * 3) + (Floor(50/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(50/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon51]
Meter=Shape
Group=Color
X=((50 * (51 % 9) * 3) + (Floor(51/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(51/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon52]
Meter=Shape
Group=Color
X=((50 * (52 % 9) * 3) + (Floor(52/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(52/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon53]
Meter=Shape
Group=Color
X=((50 * (53 % 9) * 3) + (Floor(53/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(53/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon54]
Meter=Shape
Group=Color
X=((50 * (54 % 9) * 3) + (Floor(54/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(54/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon55]
Meter=Shape
Group=Color
X=((50 * (55 % 9) * 3) + (Floor(55/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(55/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon56]
Meter=Shape
Group=Color
X=((50 * (56 % 9) * 3) + (Floor(56/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(56/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon57]
Meter=Shape
Group=Color
X=((50 * (57 % 9) * 3) + (Floor(57/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(57/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon58]
Meter=Shape
Group=Color
X=((50 * (58 % 9) * 3) + (Floor(58/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(58/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon59]
Meter=Shape
Group=Color
X=((50 * (59 % 9) * 3) + (Floor(59/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(59/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon60]
Meter=Shape
Group=Color
X=((50 * (60 % 9) * 3) + (Floor(60/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(60/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon61]
Meter=Shape
Group=Color
X=((50 * (61 % 9) * 3) + (Floor(61/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(61/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon62]
Meter=Shape
Group=Color
X=((50 * (62 % 9) * 3) + (Floor(62/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(62/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon63]
Meter=Shape
Group=Color
X=((50 * (63 % 9) * 3) + (Floor(63/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(63/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon64]
Meter=Shape
Group=Color
X=((50 * (64 % 9) * 3) + (Floor(64/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(64/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon65]
Meter=Shape
Group=Color
X=((50 * (65 % 9) * 3) + (Floor(65/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(65/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon66]
Meter=Shape
Group=Color
X=((50 * (66 % 9) * 3) + (Floor(66/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(66/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon67]
Meter=Shape
Group=Color
X=((50 * (67 % 9) * 3) + (Floor(67/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(67/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon68]
Meter=Shape
Group=Color
X=((50 * (68 % 9) * 3) + (Floor(68/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(68/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon69]
Meter=Shape
Group=Color
X=((50 * (69 % 9) * 3) + (Floor(69/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(69/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon70]
Meter=Shape
Group=Color
X=((50 * (70 % 9) * 3) + (Floor(70/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(70/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon71]
Meter=Shape
Group=Color
X=((50 * (71 % 9) * 3) + (Floor(71/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(71/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon72]
Meter=Shape
Group=Color
X=((50 * (72 % 9) * 3) + (Floor(72/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(72/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon73]
Meter=Shape
Group=Color
X=((50 * (73 % 9) * 3) + (Floor(73/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(73/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon74]
Meter=Shape
Group=Color
X=((50 * (74 % 9) * 3) + (Floor(74/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(74/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor1] | Fill Color [FileColor1]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon75]
Meter=Shape
Group=Color
X=((50 * (75 % 9) * 3) + (Floor(75/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(75/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon76]
Meter=Shape
Group=Color
X=((50 * (76 % 9) * 3) + (Floor(76/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(76/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor2] | Fill Color [FileColor2]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon77]
Meter=Shape
Group=Color
X=((50 * (77 % 9) * 3) + (Floor(77/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(77/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon78]
Meter=Shape
Group=Color
X=((50 * (78 % 9) * 3) + (Floor(78/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(78/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor3] | Fill Color [FileColor3]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon79]
Meter=Shape
Group=Color
X=((50 * (79 % 9) * 3) + (Floor(79/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(79/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1
[Hexagon80]
Meter=Shape
Group=Color
X=((50 * (80 % 9) * 3) + (Floor(80/9) % 2) * 50 * 1.5)
Y=(((Sqrt(3)/2)*50) * Floor(80/9))
Shape=Path MyPath | StrokeWidth 2 | Stroke Color [FileColor4] | Fill Color [FileColor4]
MyPath=0,((Sqrt(3)/2)*50) | LineTo (50/2),0 | LineTo (50/2 + 50),0 | LineTo (50*2),((Sqrt(3)/2)*50) | LineTo (50/2 + 50),(((Sqrt(3)/2)*50)*2) | LineTo (50/2),(((Sqrt(3)/2)*50)*2) | ClosePath 1